version: "3"

networks:
  dda:
    external:
      name: dda

services:
  odoodb-11:
    container_name: odoodb-11
    image: postgres:11
    environment:
      - "POSTGRES_USER=odoo"
      - "POSTGRES_PASSWORD=odoo"
      - "POSTGRES_DB=postgres"
    networks:
      - dda

  odoo-11:
    container_name: odoo-11
    image: odoo:11
    external_links:
      - odoodb-11:db
    ports:
      - 8068:8069
    networks:
      - dda
    volumes:
      - ../add_ons:/mnt/extra-addons